import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const index = readFileSync(new URL("../internal/httpapi/web/index.html", import.meta.url), "utf8");
const app = readFileSync(new URL("../internal/httpapi/web/app.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../internal/httpapi/web/styles.css", import.meta.url), "utf8");

test("Living Topics activates local evidence and maintains understanding automatically", () => {
  assert.match(index, /id="topics-view-button"[^>]*>.*Living Topics.*id="living-topics-nav-badge"/);
  assert.match(index, /LIVING TOPICS · FULL STAGE 1/);
  assert.match(index, /bounded local activation scan proposes older Library evidence for review/);
  assert.match(index, /id="living-topic-create-form"/);
  assert.match(index, /id="living-topic-evidence-search-form"/);
  assert.match(index, /id="living-topic-detail-tabs"[^>]*role="tablist"/);
  assert.match(index, /id="living-topic-snapshot-tab"[^>]*aria-selected="true"[^>]*>Understanding<\/button>/);
  assert.match(index, /id="living-topic-evidence-tab"[^>]*>Manage evidence<\/button>/);
  assert.ok(index.indexOf('id="living-topic-snapshot-panel"') < index.indexOf('id="living-topic-evidence-panel"'));
  assert.match(index, /id="living-topic-snapshot-form"/);
  assert.match(index, /id="living-topic-snapshot-button"[^>]*type="submit"[^>]*>Refresh now<\/button>/);
  assert.match(index, /id="living-topic-snapshot-status"[^>]*role="status"[^>]*aria-live="polite"/);
  assert.match(index, /Updates automatically after topic evidence changes/);
  assert.match(index, /new history version is published only when the understanding changes materially/);
  assert.match(index, /id="living-topic-description"[^>]*maxlength="1200"/);
  assert.match(index, /id="living-topic-aliases"[^>]*maxlength="960"/);
  assert.match(index, /id="living-topic-includes"[^>]*maxlength="1200"/);
  assert.match(index, /id="living-topic-excludes"[^>]*maxlength="1200"/);
  assert.match(index, /id="living-topic-activation-button"[^>]*>Scan again<\/button>/);
  assert.match(index, /id="living-topic-suggestions"/);
  assert.match(index, /id="living-topic-move-status"[^>]*role="status"/);
});

test("Living Topics UI exposes bounded membership and automatic understanding state", () => {
  assert.match(app, /async function addLivingTopicMember\(memoryItemId\)/);
  assert.match(app, /async function removeLivingTopicMember\(memoryItemId\)/);
  assert.match(app, /async function moveLivingTopicMember\(memoryItemId, toTopicId\)/);
  assert.match(app, /async function undoLivingTopicMemberMove\(\)/);
  assert.match(app, /async function createLivingTopicSnapshot\(event\)/);
  assert.match(app, /function scheduleLivingTopicUnderstandingPoll\(topicId, announce = false\)/);
  assert.match(app, /async function requestLivingTopicActivation\(\)/);
  assert.match(app, /async function reviewLivingTopicCandidate\(memoryItemId, action\)/);
  assert.match(app, /function scheduleLivingTopicActivationPoll\(topicId\)/);
  assert.match(app, /async function refreshLivingTopicNotificationProjection\(\)/);
  assert.match(app, /async function selectLivingTopic\(id\)/);
  assert.match(app, /buildLivingTopicSeenPath\(id\)/);
  assert.match(app, /fresh\.textContent = topic\.newEvidenceCount > 1 \? `New \$\{topic\.newEvidenceCount\}` : "New"/);
  assert.match(app, /\[\["Accept", "accept"\], \["Reject", "reject"\]\]/);
  assert.match(app, /undo\.textContent = "Undo"/);
  assert.match(app, /Understanding could not be refreshed:/);
  assert.match(app, /Current understanding is up to date\./);
  assert.match(app, /card\.dataset\.snapshotId = snapshot\.id/);
  assert.match(app, /What changed since the previous understanding/);
  assert.match(app, /Uncertainty and conflicts/);
  assert.match(app, /detail\.members\.length >= 20/);
  assert.match(app, /membership\.origin === "automatic"/);
  assert.match(app, /No snapshot is fully supported by the current topic evidence/);
  assert.match(app, /snapshot\.evidenceAvailability === "available"/);
  assert.match(styles, /\.living-topics-layout \{[^}]*grid-template-columns/);
  assert.match(styles, /\.living-topic-snapshot-card \{/);
  assert.match(styles, /\.living-topic-move-status \{/);
  assert.match(styles, /\.view-notification-badge, \.living-topic-new-badge \{/);
  assert.match(styles, /\.living-topics-layout \{ grid-template-columns: 1fr; \}/);
});
