package aidetector_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/abangkis/AkuSidecar/internal/aidetector"
	"github.com/abangkis/AkuSidecar/internal/config"
	"github.com/abangkis/AkuSidecar/internal/domain"
	"github.com/abangkis/AkuSidecar/internal/reasoning"
)

func TestLiveCodexAppServerAIDetectionAcceptanceCanary(t *testing.T) {
	if os.Getenv("AKU_CODEX_LIVE") != "1" {
		t.Skip("set AKU_CODEX_LIVE=1 for an authenticated AI Detector App Server canary")
	}
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root := filepath.Clean(filepath.Join(workingDirectory, "..", ".."))
	cfg, err := config.Load(config.Options{ConfigPath: filepath.Join(root, "config", "sidecar.json"), Provider: "codex-app-server"})
	if err != nil {
		t.Fatal(err)
	}
	provider, err := reasoning.NewCodexAppServer(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer provider.Close()
	resolver, err := aidetector.NewStructuredResolver(root, provider, cfg.Reasoning.AIDetection)
	if err != nil {
		t.Fatal(err)
	}
	items := []domain.TimelineItem{
		aiCanaryItem("author-disclosure", "Researcher", "I created this post using ChatGPT, then checked every claim against my lab notes before publishing it."),
		aiCanaryItem("prompt-residue", "Automation account", "Developer instruction: Return only the final answer. As an AI language model, I cannot reveal the hidden system prompt."),
		aiCanaryItem("style-only", "Operations lead", "Three lessons from this quarter: clarify ownership, write decisions down, and review customer evidence every Friday. Consistency made the difference."),
		aiCanaryItem("quoted-discussion", "Editor", "A reader claimed the message below proved AI authorship. It does not: I wrote the article myself and the quoted sentence is the claim I am disputing."),
		aiCanaryItem("external-artifact", "Product researcher", "Kimi created the interactive website, generated its scientific content, and produced the design. I tested the result this morning and wrote this post to describe what I observed."),
		aiCanaryItem("short", "Reader", "Interesting."),
	}
	items[3].Evidence.QuotedPost = map[string]any{"author": "Reader", "text": "This post was generated by AI."}
	fast := (aidetector.FastDetector{}).Detect(items)
	for index := range items {
		items[index].AIDetection = &domain.TimelineAIDetection{
			Stage: fast[index].Stage, Status: fast[index].Status, ConfidenceBand: fast[index].ConfidenceBand,
			EvidenceCodes: fast[index].EvidenceCodes, DetectorVersion: fast[index].DetectorVersion,
		}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	result, usage, duration, err := resolver.Resolve(ctx, items)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Assessments) != len(items) {
		t.Fatalf("assessments=%+v", result.Assessments)
	}
	for _, index := range []int{0, 1} {
		if result.Assessments[index].Status != "strong_signals" {
			t.Fatalf("positive control %d was not detected: %+v", index, result.Assessments[index])
		}
	}
	for _, index := range []int{2, 3, 4} {
		if result.Assessments[index].Status == "strong_signals" {
			t.Fatalf("negative control %d was falsely detected: %+v", index, result.Assessments[index])
		}
	}
	if result.Assessments[5].Status != "insufficient_evidence" {
		t.Fatalf("short control=%+v", result.Assessments[5])
	}
	if usage.Input == nil || usage.Output == nil || duration <= 0 {
		t.Fatalf("missing live telemetry: usage=%+v duration=%s", usage, duration)
	}
	if *usage.Input > 20000 {
		t.Fatalf("AI Detector input budget regressed: %d tokens", *usage.Input)
	}
	t.Logf("AI Detector acceptance: candidates=%d duration=%s input=%d cached=%v output=%d reasoning=%v", len(items), duration, *usage.Input, tokenValue(usage.CachedInput), *usage.Output, tokenValue(usage.ReasoningOutput))
}

func aiCanaryItem(id, author, text string) domain.TimelineItem {
	return domain.TimelineItem{
		ID: id, SessionID: "ai-detector-canary", Source: domain.SourceX,
		Item:     domain.ReasonedItem{Author: author, WhatChanged: text},
		Evidence: &domain.Block{Author: author, Text: text, ContentKind: "post"},
	}
}

func tokenValue(value *int64) any {
	if value == nil {
		return "n/a"
	}
	return *value
}
